## Introdução ao Numpy
Biblioteca focada em manipulação eficiente de arrays (matrizes) multidimensionais

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr)) # Tipo de dados

print("Original array", arr) # Imprime o array original
print("Array Mean:", np.mean(arr)) # Média
print("Array Sum", np.sum(arr)) # Soma
print("Array Squared", np.square(arr)) # Array elevado ao quadrado

<class 'numpy.ndarray'>
Original array [1 2 3 4 5]
Array Mean: 3.0
Array Sum 15
Array Squared [ 1  4  9 16 25]


In [10]:
# Criar um array 2D
matrix2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("\n2D Array:")
print(matrix2d)
print("Matrix Transpose") # Matriz transposta
print(matrix2d.T) # Transforma os elementos da linha e transforma em colunas
print(matrix2d.ndim) # Chega a dimensão


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix Transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]]
2


In [11]:
# 3D
matrix3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(matrix3d)
print("Transposta", "\n", matrix3d.T)
print(matrix3d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Transposta 
 [[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]
3


In [17]:
# Índice 
arr = np.array([1, 2, 3, 4])
print("2º elemento: ", arr[1]) # 2º elemento

arr2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2º elemento da 1ª linha: ", arr2d[0, 1])

print("Último elemento da segunda linha: ", arr2d[1, -1])

2º elemento:  2
2º elemento da 1ª linha:  2
Último elemento da segunda linha:  10


In [ ]:
# Slicing
# Pegar elementos de um índice dado para outro índice dado.
# Fatiamento em vez do índice, assim: [start:end].
# Também podemos definir o incremento, assim: [start:end:step].
# Se não passarmos o parâmetro `start`, ele será considerado 0.
# Se não passarmos o parâmetro `end`, ele será considerado o comprimento da matriz nessa dimensão.
# Se não passarmos o parâmetro `step`, ele será considerado 1.

# https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

In [ ]:
# Copia de arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# View - Altera a original
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# Checando Copy and View
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

# A cópia retorna None.
# A visualização retorna o array original.
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [23]:
# Iterando
# 1D
print("1D")
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

# 2D
print("2D")
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr2d:
  print(x)
  
# Iterar sobre cada elemento escalar da matriz bidimensional:
print("2D cada elemento:")
for x in arr2d:
  for y in x:
    print(y)

1D
1
2
3
2D
[1 2 3]
[4 5 6]
2D cada elemento:
1
2
3
4
5
6


In [27]:
# Concatenação

# 1D
print("Concatenação 1D")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

# 2D
print("Concatenação 2D")
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1) # onde o array será adicional, default = 0
print(arr)

Concatenação 1D
[1 2 3 4 5 6]
Concatenação 2D
[[1 2 5 6]
 [3 4 7 8]]
